### ISSUE TITLE
How to fix this issue

### ISSUE THREAD

**Issue by leolin65** [gordon-chenmo/UTRAD#1]
Hi,

Thanks to share your code.
I run "python main.py --dataset_name screw" and happen below issue.
Could you help me to fix it.
Thank you.

>python main.py --dataset_name screw
activation: gelu
b1: 0.5
b2: 0.999
batch_size: 2
data_root: ./datasets/
dataset_name: screw
epoch_num: 150
epoch_start: 0
exp_name: Exp0-r18
factor: 1
image_result_dir: result_images
lr: 0.0001
model_result_dir: saved_models
n_cpu: 1
num_row: 4
seed: 233
unalign_test: False
validation_image_dir: validation_images
device cuda:0
save_dir Exp0-r18-screw/saved_models/checkpoint.pth
train_dataloader <torch.utils.data.dataloader.DataLoader object at 0x0000018D07759820>
test_dataloader <torch.utils.data.dataloader.DataLoader object at 0x0000018D07782EB0>
activation: gelu
b1: 0.5
b2: 0.999
batch_size: 2
data_root: ./datasets/
dataset_name: screw
epoch_num: 150
epoch_start: 0
exp_name: Exp0-r18
factor: 1
image_result_dir: result_images
lr: 0.0001
model_result_dir: saved_models
n_cpu: 1
num_row: 4
seed: 233
unalign_test: False
validation_image_dir: validation_images
device cuda:0
save_dir Exp0-r18-screw/saved_models/checkpoint.pth
train_dataloader <torch.utils.data.dataloader.DataLoader object at 0x000002539E016370>
test_dataloader <torch.utils.data.dataloader.DataLoader object at 0x00000253830CAB20>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\ProgramData\Anaconda3\envs\env1\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\ProgramData\Anaconda3\envs\env1\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "D:\ProgramData\Anaconda3\envs\env1\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\ProgramData\Anaconda3\envs\env1\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "D:\ProgramData\Anaconda3\envs\env1\lib\runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "D:\ProgramData\Anaconda3\envs\env1\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "D:\ProgramData\Anaconda3\envs\env1\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Code\UTRAD-main\main.py", line 96, in <module>
    for i,(filename, batch) in enumerate(train_dataloader):
  File "D:\ProgramData\Anaconda3\envs\env1\lib\site-packages\torch\utils\data\dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "D:\ProgramData\Anaconda3\envs\env1\lib\site-packages\torch\utils\data\dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "D:\ProgramData\Anaconda3\envs\env1\lib\site-packages\torch\utils\data\dataloader.py", line 918, in __init__
    w.start()
  File "D:\ProgramData\Anaconda3\envs\env1\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "D:\ProgramData\Anaconda3\envs\env1\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\ProgramData\Anaconda3\envs\env1\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "D:\ProgramData\Anaconda3\envs\env1\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "D:\ProgramData\Anaconda3\envs\env1\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "D:\ProgramData\Anaconda3\envs\env1\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by gordon-chenmo** [comment]
It's a bug when running code on windows or mac, we fix it at c0227ade61854a58dd1c2e23bf10970209012a98
